Adding memcached tests
bprashan/curated_apps pull request #56
Opened 2023-02-28 12:10 UTC by anjalirai-intel

[Memcached_logs.txt](https://github.com/bprashan/curated_apps/files/10850077/Memcached_logs.txt)
Added logs for memcached tests and 1 redis test

2023-02-28 13:47 UTC, jinengandhi-intel approved these changes

2023-02-28 13:48 UTC, jinengandhi-intel requested changes
Can we add some sanity label for memcached test?

2023-02-28 15:24 UTC, anjalirai-intel commented
> Can we add some sanity label for memcached test?

I have added sanity label for memcached default, let me know if we need to add it to other test cases

2023-03-01 03:50 UTC, jinengandhi-intel approved these changes

2023-03-31 04:55 UTC, merged